Repository dusk-network/plonk, pull requests merged in 2020-07, with the labels that each got.

#258 Fix logic_constraint assertion bug
  Cargo.toml
  src/constraint_system/logic.rs
Labels: API-design, constraint_system, type:bug, type:feature

#255 ECC gate
  Cargo.toml
  src/constraint_system/arithmetic.rs
  src/constraint_system/boolean.rs
  src/constraint_system/composer.rs
  src/constraint_system/ecc/gates.rs
  src/constraint_system/ecc/mod.rs
  src/constraint_system/logic.rs
  src/constraint_system/mod.rs
  src/constraint_system/range.rs
  src/proof_system/linearisation_poly.rs
  src/proof_system/preprocess.rs
  src/proof_system/proof.rs
  src/proof_system/prover.rs
  src/proof_system/quotient_poly.rs
  src/proof_system/widget/ecc/mod.rs
  src/proof_system/widget/ecc/proverkey.rs
  src/proof_system/widget/ecc/verifierkey.rs
  src/proof_system/widget/mod.rs
Labels: area:cryptography, composer-custom-gates, type:feature

#260 Export curve crates in plonk
  Cargo.toml
  src/lib.rs
Labels: API-design

#261 Bump to v0.2.0
  CHANGELOG.md
  Cargo.toml
  src/prelude.rs
Labels: API-design

#267 Implement a method for constraint-to-const witnes
  CHANGELOG.md
  src/constraint_system/composer.rs
Labels: API-design, constraint_system, end-user-utility, type:feature

#266 Remove pub visibility of Proof::verify()
  src/proof_system/proof.rs
Labels: API-design

#269 Bump to v0.2.2
  CHANGELOG.md
  Cargo.toml
Labels: type:bug
