Repository dusk-network/plonk, pull requests merged in 2020-04, with the labels that each got.

#165 Build clippy linting structure & criteria
  .travis.yml
  src/bit_iterator.rs
  src/commitment_scheme/kzg10/key.rs
  src/commitment_scheme/kzg10/mod.rs
  src/commitment_scheme/kzg10/srs.rs
  src/commitment_scheme/mod.rs
  src/constraint_system/mod.rs
  src/constraint_system/standard/composer.rs
  src/constraint_system/standard/linearisation_poly.rs
  src/constraint_system/standard/mod.rs
  src/constraint_system/standard/preprocessed_circuit.rs
  src/constraint_system/standard/proof.rs
  src/constraint_system/variable.rs
  src/constraint_system/widget/arithmetic.rs
  src/constraint_system/widget/mod.rs
  src/constraint_system/widget/permutation.rs
  src/constraint_system/widget/range.rs
  src/fft/domain.rs
  src/fft/mod.rs
  src/fft/polynomial.rs
  src/lib.rs
  src/permutation/mod.rs
  src/permutation/permutation.rs
  src/transcript.rs
  src/util.rs
Labels: 3rd iteration, enhancement

#161 Turbo Composer logic_gate addition
  src/constraint_system/standard/composer.rs
  src/constraint_system/standard/linearisation_poly.rs
  src/constraint_system/standard/preprocessed_circuit.rs
  src/constraint_system/standard/proof.rs
  src/constraint_system/standard/quotient_poly.rs
  src/constraint_system/widget/logic.rs
  src/constraint_system/widget/mod.rs
  src/fft/polynomial.rs
  src/util.rs
Labels: 3rd iteration, constraint_system, enhancement, review

#135 Docs skeleton
  .gitignore
  .travis.yml
  Cargo.toml
  Makefile
  docs/katex-header.html
  docs/notes-KZG10.md
  docs/notes-commitments.md
  docs/notes-composer.md
  docs/notes-intro.md
  docs/notes-pa.md
  docs/notes-pp.md
  docs/notes-prove-verify.md
  docs/notes-snark.md
  src/lib.rs
Labels: 3rd iteration, documentation, review

#181 Cleaning up comments
  src/commitment_scheme/kzg10/mod.rs
  src/commitment_scheme/kzg10/srs.rs
  src/commitment_scheme/mod.rs
  src/constraint_system/mod.rs
  src/constraint_system/standard/composer.rs
  src/constraint_system/standard/mod.rs
  src/constraint_system/standard/preprocessed_circuit.rs
  src/constraint_system/widget/permutation.rs
  src/fft/domain.rs
  src/fft/mod.rs
  src/fft/polynomial.rs
  src/permutation/permutation.rs
Labels: 3rd iteration, documentation, enhancement

#184 Add q_c as a parameter into the mul and add helper functions
  src/constraint_system/standard/composer.rs
Labels: circuit-performance, composer-custom-gates, constraint_system, end-user-utility

#187 Merge Barycentric Evaluation
  src/constraint_system/standard/proof.rs
Labels: circuit-performance, composer-custom-gates

#188 Fix bug
  src/constraint_system/standard/composer.rs
  src/permutation/permutation.rs
Labels: bug, composer-custom-gates

#175 Document commitment schemes
  docs/notes-KZG10.md
  docs/notes-commitments.md
  docs/notes-composer.md
  docs/notes-intro.md
  docs/notes-pa.md
  docs/notes-pp.md
  docs/notes-prove-verify.md
  src/commitment_scheme/kzg10/key.rs
  src/lib.rs
Labels: 3rd iteration, documentation

#183 Add serde support for crate's data structures
  Cargo.toml
  benchmarks/plonk_benchmarks.rs
  src/commitment_scheme/kzg10/key.rs
  src/commitment_scheme/kzg10/mod.rs
  src/commitment_scheme/kzg10/srs.rs
  src/constraint_system/standard/linearisation_poly.rs
  src/constraint_system/standard/preprocessed_circuit.rs
  src/constraint_system/standard/proof.rs
  src/constraint_system/widget/arithmetic.rs
  src/constraint_system/widget/logic.rs
  src/constraint_system/widget/mod.rs
  src/constraint_system/widget/permutation.rs
  src/constraint_system/widget/range.rs
  src/fft/domain.rs
  src/fft/evaluations.rs
  src/fft/polynomial.rs
  src/lib.rs
Labels: end-user-utility, enhancement, serialization-serde

#193 Clean up Visibility of functions and Comments
  src/constraint_system/standard/composer.rs
  src/constraint_system/standard/proof.rs
  src/constraint_system/variable.rs
  src/constraint_system/widget/arithmetic.rs
  src/constraint_system/widget/logic.rs
  src/constraint_system/widget/permutation.rs
  src/constraint_system/widget/range.rs
  src/fft/domain.rs
  src/fft/evaluations.rs
  src/fft/polynomial.rs
  src/permutation/constants.rs
  src/permutation/permutation.rs
  src/transcript.rs
Labels: API-design, documentation

#192 Add example folders in rust for the library usage methodologies
  Cargo.toml
  examples/.prep_circ_2_3.bin
  examples/.proof_ko_2_3.bin
  examples/.proof_ok_2_3.bin
  examples/.public_params.bin
  examples/0_setup_srs.rs
  examples/1_compose_prove_verify.rs
  examples/2_gadget_orientation.rs
  examples/3_final_gadget_orientation.rs
  examples/readme.md
  src/constraint_system/standard/composer.rs
  src/permutation/permutation.rs
Labels: documentation, end-user-utility, enhancement

#200 Add "trace" and "trace-print" features for circuit debugging.
  Cargo.toml
  src/constraint_system/standard/composer.rs
Labels: API-design, end-user-utility, enhancement

#201 Pad witness in Prover
  src/constraint_system/standard/composer.rs
  src/permutation/permutation.rs
Labels: rust-performance

#202 Modifies the structure of the module to separate the constraint system from the proof system
  examples/1_compose_prove_verify.rs
  examples/2_gadget_orientation.rs
  examples/3_final_gadget_orientation.rs
  src/constraint_system/composer.rs
  src/constraint_system/mod.rs
  src/constraint_system/standard/mod.rs
  src/lib.rs
  src/proof_system/linearisation_poly.rs
  src/proof_system/mod.rs
  src/proof_system/preprocessed_circuit.rs
  src/proof_system/proof.rs
  src/proof_system/quotient_poly.rs
  src/proof_system/widget/arithmetic.rs
  src/proof_system/widget/logic.rs
  src/proof_system/widget/mod.rs
  src/proof_system/widget/permutation.rs
  src/proof_system/widget/range.rs
Labels: API-design, constraint_system, end-user-utility, enhancement

#182 Inserting proof notes
  docs/notes-prove-verify.md
  docs/notes-snark.md
Labels: 3rd iteration, documentation

#204 Removes the un-needed padding constraints
  src/commitment_scheme/kzg10/mod.rs
  src/constraint_system/composer.rs
Labels: enhancement

#203 Add codecov & GH-pages auto doc-uploads
  .travis.yml
Labels: documentation, end-user-utility, enhancement, travis-ci

#209 Examples decoupling
  .travis.yml
  examples/.prep_circ_2_3.bin
  examples/.proof_ko_2_3.bin
  examples/.proof_ok_2_3.bin
  examples/.public_params.bin
  examples/0_setup_srs.rs
  examples/1_compose_prove_verify.rs
  examples/2_gadget_orientation.rs
  examples/3_0_setup_for_gadgets.rs
  examples/3_1_final_gadget_orientation.rs
  examples/readme.md
Labels: documentation, travis-ci

#210 Bump to 0.1.0
  CHANGELOG.md
  CONTRIBUTING.md
  Cargo.toml
  README.md
  benchmarks/plonk_benchmarks.rs
  examples/1_compose_prove_verify.rs
  examples/2_gadget_orientation.rs
  examples/3_0_setup_for_gadgets.rs
  examples/3_1_final_gadget_orientation.rs
  src/bit_iterator.rs
  src/commitment_scheme/kzg10/key.rs
  src/commitment_scheme/kzg10/mod.rs
  src/commitment_scheme/kzg10/srs.rs
  src/constraint_system/composer.rs
  src/constraint_system/variable.rs
  src/fft/domain.rs
  src/fft/evaluations.rs
  src/fft/polynomial.rs
  src/lib.rs
  src/permutation/constants.rs
  src/permutation/permutation.rs
  src/proof_system/linearisation_poly.rs
  src/proof_system/preprocessed_circuit.rs
  src/proof_system/proof.rs
  src/proof_system/quotient_poly.rs
  src/proof_system/widget/arithmetic.rs
  src/proof_system/widget/logic.rs
  src/proof_system/widget/mod.rs
  src/proof_system/widget/permutation.rs
  src/proof_system/widget/range.rs
  src/transcript.rs
  src/util.rs
Labels: documentation, enhancement

#213 Update CHANGELOG & travis binary filenames
  .travis.yml
  CHANGELOG.md
Labels: documentation, travis-ci

#215 Check Doc
  examples/0_setup_srs.rs
  examples/1_compose_prove_verify.rs
  examples/2_gadget_orientation.rs
  examples/3_0_setup_for_gadgets.rs
  examples/3_1_final_gadget_orientation.rs
  examples/readme.md
Labels: documentation, end-user-utility

#211 Initial Prover and Verifier abstraction
  examples/0_setup_srs.rs
  examples/1_compose_prove_verify.rs
  examples/2_gadget_orientation.rs
  examples/3_0_setup_for_gadgets.rs
  examples/3_1_final_gadget_orientation.rs
  src/commitment_scheme/mod.rs
  src/constraint_system/composer.rs
  src/proof_system/mod.rs
  src/proof_system/preprocessed_circuit.rs
  src/proof_system/prover.rs
  src/proof_system/verifier.rs
Labels: API-design, blocking, end-user-utility, enhancement
