Repository dusk-network/plonk, pull requests merged in 2020-03, with the labels that each got.

#137 [zexe_branch] Fix `add` and `mul` to evaluate `w_o` correct
  src/cs/composer.rs
Labels: 2nd iteration, blocking, constraint_system, invalid

#139 Use new msm_var_base impl of Bls12_381
  Cargo.lock
  src/commitment_scheme/kzg10/key.rs
  src/constraint_system/standard/proof.rs
Labels: 2nd iteration, performance

#149 Fix references usage
  src/constraint_system/standard/linearisation_poly.rs
  src/constraint_system/standard/proof.rs
  src/fft/domain.rs
  src/fft/polynomial.rs
  src/permutation/grand_product_lineariser.rs
  src/permutation/grand_product_quotient.rs
  src/permutation/permutation.rs
Labels: 3rd iteration, enhancement

#151 Adds a width-4 Mul gate
  src/constraint_system/standard/composer.rs
Labels: 3rd iteration, enhancement

#152 Take fft_const from Bls lib
  Cargo.lock
  src/fft/constants.rs
  src/fft/domain.rs
  src/fft/mod.rs
Labels: 3rd iteration, enhancement

#154 Move 4n evals computation to pre-processing stage.
  src/constraint_system/standard/composer.rs
  src/constraint_system/standard/preprocessed_circuit.rs
  src/constraint_system/standard/quotient_poly.rs
Labels: 2nd iteration, enhancement, performance

#155 Adds range constraint gate
  src/bit_iterator.rs
  src/constraint_system/standard/composer.rs
  src/constraint_system/standard/linearisation_poly.rs
  src/constraint_system/standard/preprocessed_circuit.rs
  src/constraint_system/standard/proof.rs
  src/constraint_system/standard/quotient_poly.rs
  src/lib.rs
  src/permutation/permutation.rs
Labels: enhancement
