Repository dusk-network/plonk, pull requests merged in 2020-11, with the labels that each got.

#319 Migrate from CI provider to GH Actions
  .github/workflows/dusk_ci.yml
  .travis.yml
  Cargo.toml
  codecov.yml
Labels: area:testing, travis-ci

#320 Add flag-featured Canon-derived ecc libs usage.
  CHANGELOG.md
  Cargo.toml
Labels: area:IPC, type:refactor

#315 Multizip version of product argument
  CHANGELOG.md
  src/permutation/permutation.rs
  src/proof_system/prover.rs
Labels: type:question
