Repository dusk-network/plonk, pull requests merged in 2021-01, with the labels that each got.

#366 Lookup changes
  src/permutation/permutation.rs
  src/proof_system/linearisation_poly.rs
  src/proof_system/prover.rs
  src/proof_system/quotient_poly.rs
  src/proof_system/widget/permutation/proverkey.rs
Labels: area:cryptography, area:testing, status:blocker, team:R&D

#349 Heavy data structures from unchecked
  CHANGELOG.md
  Cargo.toml
  src/bit_iterator.rs
  src/circuit_builder.rs
  src/commitment_scheme/kzg10/key.rs
  src/commitment_scheme/kzg10/srs.rs
  src/constraint_system/ecc/scalar_mul/fixed_base/mod.rs
  src/constraint_system/ecc/scalar_mul/variable_base/mod.rs
  src/constraint_system/logic.rs
  src/constraint_system/range.rs
  src/fft/polynomial.rs
  src/lib.rs
  src/proof_system/linearisation_poly.rs
  src/proof_system/proof.rs
  src/proof_system/widget/mod.rs
  src/serialisation.rs
  src/transcript.rs
  src/util.rs
Labels: status:minor, team:Core, type:feature, type:performance, type:tech-debt

#372 Upgrade canonical to v0.5 ( #371 )
  CHANGELOG.md
  Cargo.toml
Labels: team:Core
