Repository dusk-network/plonk, pull requests merged in 2021-06, with the labels that each got.

#537 Remove `external_doc` and `nightly` feature
  .github/workflows/dusk_ci.yml
  CHANGELOG.md
  Cargo.toml
  Makefile
  README.md
  rust-toolchain
  src/constraint_system/arithmetic.rs
  src/constraint_system/boolean.rs
  src/constraint_system/composer.rs
  src/constraint_system/ecc/mod.rs
  src/lib.rs
  src/proof_system/preprocess.rs
Labels: team:Core

#535 Add `add_affine_to_circuit_description`to composer
  CHANGELOG.md
  src/constraint_system/ecc/mod.rs
Labels: team:Core

#538 Release 0.8.1
  .github/workflows/dusk_ci.yml
  CHANGELOG.md
  Cargo.toml
  Makefile
  README.md
  rust-toolchain
  src/constraint_system/arithmetic.rs
  src/constraint_system/boolean.rs
  src/constraint_system/composer.rs
  src/constraint_system/ecc/mod.rs
  src/lib.rs
  src/proof_system/preprocess.rs
Labels: team:Core

#530 Refactor Hash constraint tables
  Cargo.toml
  src/constraint_system/composer.rs
  src/constraint_system/helper.rs
  src/constraint_system/zelbet.rs
  src/plookup/table/hash_tables/constants.rs
  src/plookup/table/hash_tables/mod.rs
  src/plookup/table/hash_tables/tables.rs
  src/plookup/table/lookup_table.rs
  src/plookup/table/mod.rs
  src/proof_system/prover.rs
Labels: area:composer-custom-gates, area:constraint_system, area:cryptography, team:R&D

#533 Change the reference document link
  CHANGELOG.md
  docs/notes-commitments.md
  docs/notes-intro.md
Labels: area:documentation, fix:bug
