Repository dusk-network/plonk, pull requests merged in 2021-03, with the labels that each got.

#420 rm uncessary match branch mentioned in #414
  CHANGELOG.md
  src/constraint_system/logic.rs
Labels: type:refactor

#423 PI handling & Circuit Builder trait refactor
  CHANGELOG.md
  Cargo.toml
  README.md
  src/circuit.rs
  src/circuit_builder.rs
  src/constraint_system/arithmetic.rs
  src/constraint_system/boolean.rs
  src/constraint_system/composer.rs
  src/constraint_system/ecc/curve_addition/fixed_base_gate.rs
  src/constraint_system/ecc/curve_addition/variable_base_gate.rs
  src/constraint_system/ecc/mod.rs
  src/constraint_system/ecc/scalar_mul/fixed_base/mod.rs
  src/constraint_system/ecc/scalar_mul/variable_base/mod.rs
  src/constraint_system/helper.rs
  src/constraint_system/logic.rs
  src/constraint_system/range.rs
  src/lib.rs
  src/permutation/permutation.rs
  src/prelude.rs
  src/proof_system/prover.rs
  src/proof_system/widget/mod.rs
Labels: team:Core

#413 Fix comment typo
  src/constraint_system/arithmetic.rs
  src/permutation/permutation.rs
  src/proof_system/preprocess.rs
  src/proof_system/widget/arithmetic/proverkey.rs
Labels: area:documentation

#431 Remove hyperlink from SNARK docs.
  docs/notes-prove-verify.md
Labels: area:documentation, team:R&D

#444 Broken links lint fix
  src/lib.rs
Labels: team:Core

#442 Use hashbrown::HashMap instead of collections::HashMap
  CHANGELOG.md
  Cargo.toml
  src/constraint_system/composer.rs
  src/permutation/permutation.rs
Labels: team:Core

#445 Add Toolchain & fmt files to repo
  rust-toolchain
  rustfmt.toml
  src/bit_iterator.rs
  src/circuit.rs
  src/commitment_scheme/kzg10/key.rs
  src/commitment_scheme/kzg10/mod.rs
  src/commitment_scheme/kzg10/srs.rs
  src/commitment_scheme/mod.rs
  src/constraint_system/arithmetic.rs
  src/constraint_system/boolean.rs
  src/constraint_system/composer.rs
  src/constraint_system/ecc/curve_addition/fixed_base_gate.rs
  src/constraint_system/ecc/curve_addition/variable_base_gate.rs
  src/constraint_system/ecc/mod.rs
  src/constraint_system/ecc/scalar_mul/fixed_base/mod.rs
  src/constraint_system/ecc/scalar_mul/variable_base/mod.rs
  src/constraint_system/helper.rs
  src/constraint_system/logic.rs
  src/constraint_system/range.rs
  src/constraint_system/variable.rs
  src/error.rs
  src/fft/domain.rs
  src/fft/evaluations.rs
  src/fft/polynomial.rs
  src/lib.rs
  src/macros.rs
  src/permutation/constants.rs
  src/permutation/permutation.rs
  src/prelude.rs
  src/proof_system/linearisation_poly.rs
  src/proof_system/preprocess.rs
  src/proof_system/proof.rs
  src/proof_system/prover.rs
  src/proof_system/quotient_poly.rs
  src/proof_system/verifier.rs
  src/proof_system/widget/arithmetic/proverkey.rs
  src/proof_system/widget/ecc/scalar_mul/fixed_base/mod.rs
  src/proof_system/widget/ecc/scalar_mul/fixed_base/proverkey.rs
  src/proof_system/widget/ecc/scalar_mul/fixed_base/verifierkey.rs
  src/proof_system/widget/logic/mod.rs
  src/proof_system/widget/logic/verifierkey.rs
  src/proof_system/widget/mod.rs
  src/proof_system/widget/permutation/proverkey.rs
  src/proof_system/widget/permutation/verifierkey.rs
  src/proof_system/widget/range/mod.rs
  src/proof_system/widget/range/proverkey.rs
  src/proof_system/widget/range/verifierkey.rs
  src/serialisation.rs
  src/util.rs
Labels: team:Core

#440 Cut visibility of crate types & functions
  CHANGELOG.md
  src/commitment_scheme/kzg10/key.rs
  src/commitment_scheme/kzg10/mod.rs
  src/commitment_scheme/kzg10/srs.rs
  src/fft/domain.rs
  src/fft/evaluations.rs
  src/fft/mod.rs
  src/fft/polynomial.rs
  src/lib.rs
  src/permutation/mod.rs
  src/permutation/permutation.rs
  src/proof_system/linearisation_poly.rs
  src/proof_system/proof.rs
  src/proof_system/widget/arithmetic/mod.rs
  src/proof_system/widget/arithmetic/proverkey.rs
  src/proof_system/widget/arithmetic/verifierkey.rs
  src/proof_system/widget/ecc/curve_addition/mod.rs
  src/proof_system/widget/ecc/curve_addition/proverkey.rs
  src/proof_system/widget/ecc/curve_addition/verifierkey.rs
  src/proof_system/widget/ecc/mod.rs
  src/proof_system/widget/ecc/scalar_mul/fixed_base/mod.rs
  src/proof_system/widget/ecc/scalar_mul/fixed_base/proverkey.rs
  src/proof_system/widget/ecc/scalar_mul/fixed_base/verifierkey.rs
  src/proof_system/widget/logic/mod.rs
  src/proof_system/widget/logic/proverkey.rs
  src/proof_system/widget/logic/verifierkey.rs
  src/proof_system/widget/mod.rs
  src/proof_system/widget/permutation/mod.rs
  src/proof_system/widget/permutation/proverkey.rs
  src/proof_system/widget/permutation/verifierkey.rs
  src/proof_system/widget/range/mod.rs
  src/proof_system/widget/range/proverkey.rs
  src/proof_system/widget/range/verifierkey.rs
  src/serialisation.rs
  src/transcript.rs
Labels: team:Core

#434 Crate serialization major refactor & standarization
  CHANGELOG.md
  Cargo.toml
  src/circuit.rs
  src/commitment_scheme/kzg10/key.rs
  src/commitment_scheme/kzg10/mod.rs
  src/commitment_scheme/kzg10/srs.rs
  src/error.rs
  src/fft/domain.rs
  src/fft/evaluations.rs
  src/fft/polynomial.rs
  src/lib.rs
  src/macros.rs
  src/proof_system/linearisation_poly.rs
  src/proof_system/proof.rs
  src/proof_system/widget/arithmetic/verifierkey.rs
  src/proof_system/widget/ecc/scalar_mul/mod.rs
  src/proof_system/widget/ecc/scalar_mul/variable_base/mod.rs
  src/proof_system/widget/logic/mod.rs
  src/proof_system/widget/mod.rs
  src/serialisation.rs
Labels: team:Core

#449 Fix Error type used for Serializable impl Proof
  src/proof_system/proof.rs
Labels: team:Core

#451 Fix canon feature related compilation errors
  CHANGELOG.md
  src/error.rs
  src/proof_system/proof.rs
Labels: team:Core

#454 Implement ID associated const for Circuit trait
  README.md
  src/circuit.rs
Labels: team:Core

#462 Change dense PI construction fn in Composer
  src/constraint_system/composer.rs
Labels: team:Core

#459 Change trim() visibility to pub
  src/commitment_scheme/kzg10/srs.rs
Labels: team:Core

#463 Release version 0.6.1
  CHANGELOG.md
  Cargo.toml
  src/commitment_scheme/kzg10/srs.rs
  src/constraint_system/composer.rs
Labels: team:Core

#467 Add `VerifierData` struct
  CHANGELOG.md
  src/circuit.rs
Labels: team:Core
